/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (4.2.3).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.example.demo.api;

import com.example.demo.model.City;
import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.multipart.MultipartFile;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
import java.util.Map;
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2023-08-31T23:19:03.508835-07:00[America/Los_Angeles]")

@Validated
@Api(value = "city", description = "the city API")
public interface CityApi {

    default CityApiDelegate getDelegate() {
        return new CityApiDelegate() {};
    }

    /**
     * GET /city/{citycode} : Get city by code
     *
     * @param citycode Goverment defined code of the city. (required)
     * @return successful operation (status code 200)
     *         or City not found (status code 404)
     */
    @ApiOperation(value = "Get city by code", nickname = "getCityByCode", notes = "", response = City.class, tags={ "city", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "successful operation", response = City.class),
        @ApiResponse(code = 404, message = "City not found") })
    @RequestMapping(value = "/city/{citycode}",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    default ResponseEntity<City> getCityByCode(@ApiParam(value = "Goverment defined code of the city.",required=true) @PathVariable("citycode") String citycode) {
        return getDelegate().getCityByCode(citycode);
    }

}
